# Build, test, and install on different versions of Ubuntu
name: Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test-install:
    strategy: 
      matrix:
        #os: [ubuntu-18.04, ubuntu-latest]
        os: [ubuntu-latest]
        build_type: [serial, openmp, debug]
        include:
          - build_type: serial
            cmake_flags: -DCMAKE_INSTALL_PREFIX=`pwd` -DCMAKE_BUILD_TYPE=Release -DELEMENTS_ENABLE_SERIAL=ON -DELEMENTS_ENABLE_OPENMP=OFF
          - build_type: openmp
            cmake_flags: -DCMAKE_INSTALL_PREFIX=`pwd` -DCMAKE_BUILD_TYPE=Release -DELEMENTS_ENABLE_SERIAL=ON -DELEMENTS_ENABLE_OPENMP=ON
          - build_type: debug
            cmake_flags: -DCMAKE_INSTALL_PREFIX=`pwd` -DCMAKE_BUILD_TYPE=Debug -DELEMENTS_ENABLE_SERIAL=ON -DELEMENTS_ENABLE_OPENMP=OFF
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    
    - name: Install MPI
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev openmpi-bin
    
    - name: Configure CMake (${{matrix.build_type}})
      run: cmake -B ${{github.workspace}}/build-${{matrix.build_type}} ${{matrix.cmake_flags}}
    
    - name: Build (${{matrix.build_type}})
      run: cmake --build ${{github.workspace}}/build-${{matrix.build_type}}
    
    - name: Install (${{matrix.build_type}})
      run: cmake --install ${{github.workspace}}/build-${{matrix.build_type}}
